### PR TITLE
Symbolic links for cython and pybind11 compilation

### LINKED ISSUE #206: [cython] cython generates .cpp files in the source tree instead of the build tree
Cython generates .cpp files from .pyx files, and writes them in the source tree instead of the build tree. Ideally, it would write them in the build tree instead.
The reason I noticed is that the following scenario happened several times to me: I build the python plugin directly from the git sources, then I modify the sources (possibly switch branch), create a user_version, build the python plugin from that user_version, and get confused because my modifications were not taken into account. Indeed, the user_version includes the stale .cpp that were lying around in src/python/gudhi, probably with a modification time just as recent as the .pyx so the build doesn't feel the need to regenerate them.
It looks like I should be more consistent, either always build a user_version, or never. Still, it may not be too hard to make the user_version generation explicitly exclude src/python/gudhi/*.cpp from the list of files to copy.

### PR DESCRIPTION
**Pull request by VincentRouvreau**
Fix #206 
To be done:
* [X] verify wheel sizes
* [X] test wheels (linux and windows ok)
* [X] do not symlink if source and target is the same file (can happen if build in sources)

### CODE REVIEW

**Review by mglisse — APPROVED** [review]
Ah, you chose to do 1 symlink per file and not one to the directory. Ok.
Did you need to enable developer mode on the ci.inria windows vm?

**Comment by VincentRouvreau** [comment]
> Ah, you chose to do 1 symlink per file and not one to the directory. Ok. Did you need to enable developer mode on the ci.inria windows vm?

If I symlink the directory, cpp files will still be generated in sources. This is the main reason of this choice.
On the ci.inria windows vm you need to be admin to create symlinks.

**Comment by mglisse** [comment]
> On the ci.inria windows vm you need to be admin to create symlinks.

Not quite, you can enable developer mode and then anyone can create it.
Should we use cmake's option to copy the file when doing a symlink failed?

(this PR seems to cause problem for the circleCI test)

**Comment by VincentRouvreau** [comment]
> > On the ci.inria windows vm you need to be admin to create symlinks.
> 
> Not quite, you can enable developer mode and then anyone can create it. Should we use cmake's option to copy the file when doing a symlink failed?

Why not. Let's see if my proposal is sufficient enough.

> (this PR seems to cause problem for the circleCI test)

Hère, on circle ci, the issue is that we build in sources `cmake .` and the actual code is trying to symlink a file to itself, which leads to an error. I will fix it.

**Comment by mglisse** [comment]
> Why not. Let's see if my proposal is sufficient enough.

Sufficient for what? I think we already have an example of 1 machine/account where building gudhi used to work but not creating symlinks.

**Pull request merged**
