### PR TITLE
Avoid crash in Alpha_complex::get_point

### PR DESCRIPTION
**Pull request by mglisse**

### CODE REVIEW

**Review by VincentRouvreau — COMMENTED** [review]
Should we also document/test the python part ? With your fix, `get_point` will throw an `IndexError`

**Comment by mglisse** [comment]
> With your fix, `get_point` will throw an `IndexError`

It already does for an argument that is negative or too large.
I am not convinced it is necessary to document that an erroneous input results in an error, but if you think it is important, I'll add a sentence.

**Comment by VincentRouvreau** [comment]
> > With your fix, `get_point` will throw an `IndexError`
> 
> It already does for an argument that is negative or too large. I am not convinced it is necessary to document that an erroneous input results in an error, but if you think it is important, I'll add a sentence.

We document the c++ exception, so yes I would document the python exception.

**Comment by VincentRouvreau** [comment]
> We document the c++ exception, so yes I would document the python exception.

"Obvious" exceptions seem to be not documented under python cf.  [numpy.genfromtxt](https://numpy.org/devdocs/reference/generated/numpy.genfromtxt.html#numpy-genfromtxt), `np.genfromtxt("unexisting_file.txt")` throws a `FileNotFoundError`

**Review by VincentRouvreau — APPROVED** [review]

**Pull request merged**
