### PR TITLE
#2: add a simplex iterator in Python

### PR DESCRIPTION
**Pull request by yagu0**
Attempt to fix the issue #2 

NOTE: get_filtration() and the introduced method get_unprocessed_filtration() return the same thing:

> f = st.get_filtration()
> g = st.get_unprocessed_filtration()
> f == g
True

So I think get_filtration() could be replaced by the simpler code of the other - temporary, internal - function. The next() method in iterator class could also be simplified (loop "for vertex in filtered_complex[0] ...").

### CODE REVIEW

**Comment by mglisse** [comment]
> I think get_filtration() could be replaced by the simpler code

Indeed, it looks like `return self.get_ptr().get_filtration()` is sufficient, cython handles the conversion.

We could also return a wrapper to std::vector which avoids doing a conversion. That would happen automatically if we were using pybind11, while in cython it requires writing the wrapper by hand IIUC. However, that doesn't seem worth the trouble, since that's not the final result we want (see the precisions I am going to add to issue #2).

**Comment by mglisse** [comment]
The global map is a clever way to handle nested loops, though it isn't as good for multithreading. But I really don't think it is necessary. I am sorry I haven't had time to look at it yet, I hope I'll find some time...

**Comment by VincentRouvreau** [comment]
While reviewing your code, I tried to do it with yield on PR #211 .
Tell me what you think about this approach.
It allows to remove the global map as @mglisse was talking about.

**Comment by VincentRouvreau** [comment]
I close this PR as we all agree that we will go with #211

**Pull request closed without merging**
