### PR TITLE
Sphinx fix layout

### LINKED ISSUE #665: [python / documentation] documentation is no more taking 100% with sphinx >= 5.0.0
With sphinx >= 5.0.0, in generated `sphinx/_static/classic.css` file, one can see:
```css
div.document {
    display: flex;
    background-color: white;
}
```

which leads to the same issue than [this python-docs-theme issue](https://github.com/python/python-docs-theme/issues/92).

If one removes the line `display: flex;`, the text takes 100% of the web page.

### PR DESCRIPTION
**Pull request by VincentRouvreau**
Use [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io)instead of python-docs-theme.
Try version switch
Try CI
* [ ] `pydata-sphinx-theme` to be installed in gudhi-deploy
* [X] Maybe test again [horiontal spacing at 100%](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#horizontal-spacing), but I could not make it work at first try. Workaround #664 - cf. https://github.com/pydata/pydata-sphinx-theme/issues/1144

A demo is available at https://gudhi.inria.fr/python/3.8.0a0/ (version switcher is only available for this version)

Fix #665

### CODE REVIEW

**Comment by mglisse** [comment]
Is ctrl+K supposed to be on top of the search field, or is it still the problem caused by the top bar?
image

**Comment by VincentRouvreau** [comment]
> Is ctrl+K supposed to be on top of the search field, or is it still the problem caused by the top bar?

Yes it is supposed to. It is nicer on [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io) because it is integrated in the top bar and open a *search window* with `Ctrl+K` on the right. They removed `Ctrl+K` on [bokeh](https://docs.bokeh.org/en/latest/docs/first_steps.html), but I could not find how.
We can remove `Ctrl+K` with a custom search bar and comment `Ctrl+K`:
```html
<form class="bd-search d-flex align-items-center" action="search.html" method="get">
  <i class="fa-solid fa-magnifying-glass"></i>
  <input type="search" class="form-control" name="q" id="search-input" placeholder="Search the docs ..." aria-label="Search the docs ..." autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">
  <!-- <span class="search-button__kbd-shortcut"><kbd class="kbd-shortcut__modifier">Ctrl</kbd>+<kbd>K</kbd></span> -->
</form>
```

Just tell me your preferences, I have no strong opinion on this.

**Comment by mglisse** [comment]
Since "ctrl-K" even hides most of what I type in the search field (I seriously doubt it is supposed to do that), I'd rather remove it, yes.

**Comment by mglisse** [comment]
Other than the ctrl-K, this looks fine.
Of course there are a few issues depending on the shape of the window, and some stylistic choices don't look optimal, but perfection doesn't exist in matters of taste... Ok for me once ctrl-K is handled.

**Comment by VincentRouvreau** [comment]
> Since "ctrl-K" even hides most of what I type in the search field (I seriously doubt it is supposed to do that), I'd rather remove it, yes.

I removed `Ctrl-K` from the search bar on [6a76fd3](https://github.com/GUDHI/gudhi-devel/pull/803/commits/6a76fd35b95b94f634414c350dc7f57ec99c7227)

**Comment by VincentRouvreau** [comment]
> Other than the ctrl-K, this looks fine. Of course there are a few issues depending on the shape of the window, and some stylistic choices don't look optimal, but perfection doesn't exist in matters of taste... Ok for me once ctrl-K is handled.

We were discussing offline about it with @tlacombe and I think the main issue is on the main page, where modules are described in a html tables. Tables disappear with modern web sites as redimension (even if you speak in terms of %) does not work well. Maybe we can imagine presenting modules differently on another PR.

**Comment by mglisse** [comment]
> Tables disappear with modern web sites as redimension (even if you speak in terms of %) does not work well. Maybe we can imagine presenting modules differently on another PR.

Indeed changing that would be a separate PR.

**Pull request merged**
