### PR TITLE
Feature/sanitizer option

### PR DESCRIPTION
**Pull request by VincentRouvreau**
A new cmake gudhi option to activate gcc/clang sanitizers. Default value is `WITH_GUDHI_SANITIZER=''`.
In a command line one can easily activate sanitizer with i.e.:
`cmake -DWITH_GUDHI_SANITIZER=address .`
This will activate debug mode (`-g`) and add the compilation flag `-fsanitize=addess`.
With MSVC, a warning message to explain the feature is not available is displayed.
It does not activate sanitizer for the python module. To be discussed.

Some material about [gcc](https://gjbex.github.io/Defensive_programming_and_debugging/BugsAtRuntime/Verification/Compilers/gcc_sanitize/) and [clang](https://oscarforner.com/blog/2016-07-13-clang-sanitizers/).

### CODE REVIEW

**Comment by mglisse** [comment]
> With MSVC, a warning message to explain the feature is not available is displayed.

https://docs.microsoft.com/en-us/cpp/sanitizers/asan ?

**Comment by VincentRouvreau** [comment]
> > With MSVC, a warning message to explain the feature is not available is displayed.
> 
> https://docs.microsoft.com/en-us/cpp/sanitizers/asan ?

Sorry, I didn't know it was available under MSVC.
I made the change on [6b373b8](https://github.com/GUDHI/gudhi-devel/pull/695/commits/6b373b821cd7426b9413c2f1155551c86870adb9) and tested it under Windows.

**Review by mglisse — COMMENTED** [review]
What does it bring exactly compared to `CXXFLAGS=-fsanitize=address cmake ...` or ` cmake -DCMAKE_CXX_FLAGS=-fsanitize=address ...`?

**Comment by VincentRouvreau** [comment]
> cmake -DCMAKE_CXX_FLAGS=-fsanitize=address .

Not that much, you are right.
Maybe a better way would be to add a `how_to_compile_gudhi_with_sanitizers.md` (or a better name) in order to explain to contributors how to deal with it.

**Pull request closed without merging**
